# Generated by Django 3.2 on 2021-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_setting_smtpemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='smtppassword',
            field=models.CharField(default=12345678, max_length=10),
            preserve_default=False,
        ),
    ]
